spring.application.name=microservice1

server.port = 8001

spring.data.mongodb.uri=mongodb+srv://admin:admin@cluster0.ulkkg90.mongodb.net/mydb?retryWrites=true&w=majority&appName=Cluster0


# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/MyDb
spring.datasource.username=postgres
spring.datasource.password=Adarsh@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
